name: lint

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest
    name: flake8-black
    steps:
      - uses: actions/checkout@v1
      - name: Set up Python 3.8
        uses: actions/setup-python@v1
        with:
          python-version: 3.8
      - name: Sort with isort
        run: |
          pip install isort
          isort -y -sp walle
      - name: Lint with flake8
        run: |
          pip install flake8
          # stop the build if there are Python syntax errors or undefined names
          flake8 walle --count --show-source --statistics
      - name: Check formatting with black
        run: |
          pip install black
          black -l 100 --check walle
